import type { VoiceId } from '../audio/types';
import { SYNTH_PRESETS } from '../audio/voices/synthPresets';
import type { SeqProject, SeqTrack } from './types';

const TRACK_NAME_BY_VOICE: Record<VoiceId, string> = {
  tone: 'Ääni',
  kick: 'Kick',
  snare: 'Snare',
  hihat: 'Hihat',
  rim: 'Rim',
  sample: 'Näyte',
  bass: SYNTH_PRESETS.bass.label,
  lead: SYNTH_PRESETS.lead.label,
  pad: SYNTH_PRESETS.pad.label,
  pluck: SYNTH_PRESETS.pluck.label,
  keys: SYNTH_PRESETS.keys.label,
};

/** The descriptive default name a track gets for a given voice (e.g.
 * "Kick", "Basso") — used both when a new track is created and to detect
 * whether a track has since been renamed by the user (see updateTrack in
 * useSequencerEngine, which only auto-renames on a voice change while the
 * name still matches this). */
export function defaultTrackNameForVoice(voiceId: VoiceId): string {
  return TRACK_NAME_BY_VOICE[voiceId];
}

/** Inserts a copy of the track right after the original — same voice,
 * settings, and steps, a fresh id (generated by the caller, so this stays
 * a deterministic pure function), and "(kopio)" appended to the name. A
 * no-op if trackId doesn't match any track. */
export function duplicateTrack(project: SeqProject, trackId: string, newId: string): SeqProject {
  const index = project.tracks.findIndex((t) => t.id === trackId);
  if (index === -1) return project;
  const original = project.tracks[index];
  const copy: SeqTrack = {
    ...original,
    id: newId,
    name: `${original.name} (kopio)`,
    steps: original.steps.map((s) => ({ ...s })),
  };
  const tracks = [...project.tracks];
  tracks.splice(index + 1, 0, copy);
  return { ...project, tracks };
}
